name: mateo
favicon: null
layout_spectrum: 0.3887488639447838
typography_spectrum: 0.27447400870732963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6178546114824712
  lightness: 0.7961193807423115
  saturation: 0.07043118844740093
  rhythmicContrast: 0.8792219017632306
purpose: []
